### ISSUE TITLE
IQ-Tree update

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/ribap#21]
There is a newer and faster version of RAxML:
https://github.com/amkozlov/raxml-ng

https://doi.org/10.1093/bioinformatics/btz305

I replaced 

```bash
raxmlHPC-PTHREADS-SSE3 -T ${task.cpus} -f a -x 1234 -p 1234 -s coreGenome_mafft.aln -n aa -m PROTGAMMAWAG -N 100
```

with 

```
raxml-ng --all --threads ${task.cpus} --msa coreGenome_mafft.aln --prefix coreGenome_mafft --msa-format FASTA --model PROTGTR+G --bs-trees 100 
```

in the raxml.nf Nextflow module using

```
condo install -c bioconda raxml-ng=0.9.0
```

The output looks like this (marked in bold is the tree that also holds the bootstrap values):

coreGenome_mafft.raxml.bestModel
coreGenome_mafft.raxml.bestTree
coreGenome_mafft.raxml.bootstraps
coreGenome_mafft.raxml.log
coreGenome_mafft.raxml.mlTrees
coreGenome_mafft.raxml.rba
coreGenome_mafft.raxml.reduced.phy
coreGenome_mafft.raxml.startTree
__coreGenome_mafft.raxml.support__

@klamkiew I think it's fairly easy to also update this in the shell script for a next release

**Comment by klamkiew** [comment]
IQ-TREE might be worth looking into as well.

**Comment by hoelzer** [comment]
yes, we should switch to IQ-Tree in a newer version actually!

**Comment by hoelzer** [comment]
Docker: `docker pull nanozoo/iqtree:2.2.0.3--ba94576`
