### ISSUE TITLE
Run Prokka with reference annotation

### ISSUE THREAD

**Issue by lisa-mariebarf** [hoelzer-lab/ribap#34]
Add the possibility to run Prokka with good quality reference genomes to ensure gene naming is consistent.
`prokka --proteins *.gbk`

**Comment by klamkiew** [comment]
but is `*.gbk` correct? To me, it looks like prokka only expects one input file with this option and then uses this for the initial annotation? The wildcard looks like several `gbk` are valid?

**Comment by lisa-mariebarf** [comment]
You are right, only one fasta file is expected as the argument for the --proteins option
`  --proteins [X]    Fasta file of trusted proteins to first annotate from (default '')
`

**Comment by hoelzer** [comment]
We (Charlotte) just recently run this and I think she provided a gbk file from NCBI.

**Comment by hoelzer** [comment]
```
 prokka --proteins <ref.gb> --outdir <folder> --prefix <prefix> <.fasta file>
```
