### ISSUE TITLE
Estimate model per MSA and then design phylogeny run

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/ribap#38]
It makes more sense to estimate a substitution model per single RIBAP group (thus MSA) instead of a single model for the concatenated MSA or just using some default one. 

This can be done via IQtree:

```
iqtree -s $ALN --mem 1G -T AUTO --threads-max 4 -nt 4 -m TEST -pre ${BN}-modeltest
```

Then, for each single MSA a model is estimated. Now, the model-MSA combination can be defined for inout of IQtree w/o the need of concatenating all MSAs into one big MSA. 

http://www.iqtree.org/doc/Advanced-Tutorial
check the section "Partitioned analysis with mixed data"

So you write a nexus file with the partition scheme and the alignment files can be specified in there too.

**Comment by klamkiew** [comment]
From the looks of it, iqtree generates single trees for each partition specified in the nexus file. Which means, in theory, we could ditch fasttree;
