### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/ribap#41]
Disk space is a serious issue in the pipeline due to the many ILPs. E.g. I just run 36 Listeria monocytogenes genomes and already after ~150/750 ILPs to solve I ran out of disk space: the work dir has ~200 GB.

What can we do about this? 

a) Big disclaimer in README and when starting the pipeline, "Attention, RIBAP needs a lot of disk space for the ILPs."
b) Delete ILPs directly after they are solved? Maybe as a default and implementing a switch to keep them for experienced users

**Comment by klamkiew** [comment]
I had something started for B while looking into the copy versus link issue -- I think deleting the majority of the ILP stuff is fine; they are, in principal, intermediate results, and if needed, one can reproduce them with the .command.sh files provided by NF anyway [or we implement a flag :)].

I'm on it :)

**Comment by klamkiew** [comment]
I think I have a working version now in my local repo, but obviously, the pipeline will start over at the ILP_build process every time I resume due to missing intermediate results.

**Comment by klamkiew** [comment]
the latest commit message here is not the latest state anymore. We solved this via the --keepILPs flag now :)
