### ISSUE TITLE
Output folder names

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/ribap#47]
atm we have 

07-msa  08-mafft  08-msa

* why two msa folders? can we give them more descriptive names?
* what's the difference between these three?

**Comment by klamkiew** [comment]
Alright;

`07-msa` is the directory where all genes belonging to the same RIBAP group are gathered in a file.
`08-mafft` is then the mafft output for each of these input files.

`08-msa` was a typo in one of our modules; should be fixed now :)
