### ISSUE TITLE
Roary crashes on test data 'Error: You need to provide at least 2 files to build a pan genome'

### ISSUE THREAD

**Issue by fischer-hub** [hoelzer-lab/ribap#63]
When running RIBAP   using the test data provided:
`nextflow run ribap.nf --fasta data/*.fasta  -profile conda,slurm`

I get a crash in `Roary`: 'Error: You need to provide at least 2 files to build a pan genome'

Is it possible that there is a `collect()` missing somewhere [here](https://github.com/hoelzer-lab/ribap/blob/main/ribap.nf#L170) around the `gff_ch`? I think roary is supposed to run on all .gff files right?

EDIT: hmm just tried the same command on a local machine using docker and it works. Seems to be HPC related then..

From the HPC again:
```
[95/df97ad] process > RIBAP:rename (1)            [100%] 1 of 1 ✔
[65/e3b4e1] process > RIBAP:prokka (1)            [100%] 1 of 1 ✔
[6c/dedd41] process > RIBAP:strain_ids            [100%] 1 of 1 ✔
[b4/e03ccd] process > RIBAP:roary (3)             [200%] 2 of 1, failed: 2
```

looks like Nextflow only picks up one of the 5 samples in /data somehow?
When I `view()` the fasta input channel it also only shows one sample. How odd..

**Comment by hoelzer** [comment]
Hey, I think the problem is you forgot the single ticks around the input:

```bash
nextflow run ribap.nf --fasta 'data/*.fasta'  -profile conda,slurm
```

Thus, only one FASTA get's inputed. 

Does it work with the single ticks?

**Comment by fischer-hub** [comment]
Yes, that fixed it indeed.. didn't know this made such a difference oh well, my bad!
