### ISSUE TITLE
Error locating web.tar.gz during HTML generation in RIBAP workflow

### ISSUE THREAD

**Issue by gouxuenan** [hoelzer-lab/ribap#69]
Hello,

I'm encountering an issue while running the RIBAP workflow, specifically in the HTML generation step. Although web.tar.gz is confirmed to be in the expected directory (/home/username/.nextflow/assets/hoelzer-lab/ribap/data/web.tar.gz), I still receive an error indicating that the file cannot be found. Here is the exact error message:

`Command error:
  cp: cannot stat '/home/username/.nextflow/assets/hoelzer-lab/ribap/data/web.tar.gz': No such file or directory`

I've double-checked the path and confirmed that web.tar.gz is present with the correct permissions. However, the workflow still fails to locate the file during execution.

Could this be related to a configuration setting in Nextflow or a potential issue with the workflow's file path handling? Any advice on resolving this error would be greatly appreciated.

Thank you!

**Comment by hoelzer** [comment]
Hey @gouxuenan thanks for using the pipeline!

Am I right that you solved the problem? If not, please feel free to reach out again

**Comment by gouxuenan** [comment]
Thank you for your response! @hoelzer 

The issue has been resolved. When I initially raised the issue, I was using version 1.0.0. After updating to version 1.1.1, the problems with Python iteration counts and HTML page generation were both fixed. Therefore, I am closing this issue. 

Many thanks for your outstanding pipeline!
