### ISSUE TITLE
Bash Install Script

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/ribap#9]
I was able to run the `INSTALL.sh` script on my local Linux System with the following adjustments:

1)
I manually soft-linked `pip` to `pip3` because the install script is checking for `pip3` explicitly 

2) 
I installed `prokka` via conda because the install script was failing (maybe due to the `tbl2asn` binary)

3) 
I manually run 
```
cpanm  Array::Utils Bio::Perl Exception::Class File::Basename File::Copy File::Find::Rule File::Grep File::Path File::Slurper File::Spec File::Temp File::Which FindBin Getopt::Long Graph Graph::Writer::Dot List::Util Log::Log4perl Moose Moose::Role Text::CSV PerlIO::utf8_strict Devel::OverloadInfo Digest::MD5::File 
```
after `ROARY` install failed. 

Then everything was working.

**Comment by hoelzer** [comment]
again what worked for me (I redid the install)

```bash
conda create -n ribap python=3.7
ln -s /home/martin/miniconda3/envs/ribap/bin/pip /home/martin/miniconda3/envs/ribap/bin/pip3
conda install -c bioconda prokka
./INSTALL.sh

export PATH=$PATH:/home/martin/ribap/bin
export PERL5LIB=$PERL5LIB:/home/martin/ribap/lib
```

Likely, I did not have to do again 
```
cpanm  Array::Utils Bio::Perl Exception::Class File::Basename File::Copy File::Find::Rule File::Grep File::Path File::Slurper File::Spec File::Temp File::Which FindBin Getopt::Long Graph Graph::Writer::Dot List::Util Log::Log4perl Moose Moose::Role Text::CSV PerlIO::utf8_strict Devel::OverloadInfo Digest::MD5::File 
```

**Comment by hoelzer** [comment]
... and then I run into
```
/home/martin/ribap/bin/ribap.sh: line 254: /home/martin/ribap/bin/bin/blast2tsv.py: No such file or directory
```

so I 
```
cp -r bin /home/martin/ribap/bin/
```

**Comment by klamkiew** [comment]
To be honest, I think we can also kick the shell scripts or at least flag them as "not maintained"
It was a nice exercise back in 2018 to do both, the install and the main script in bash, but it doesn't make any sense to use those in my eyes :)

**Comment by hoelzer** [comment]
+1
